generate_field_value:
  description: >
    주어진 폼 키들에 대해 전문적이고 현실적인 값을 생성하세요.
    
    **입력 정보**:
    - 리포트 내용 또는 이전 작업 내용 : {report_content}
    - 워크플로우 단계: {topic}
    - 대상 폼 키들: {text_form_keys}
    - 사용자 정보: {user_info}
    
    **핵심 규칙**:
    1. **정확한 키 매칭**: text_form_keys에 지정된 키에 대해서만 값 생성
    2. **평면 JSON 구조**: 중첩 객체나 추가 필드 절대 금지
    3. **전문적 품질**: 구체적이고 상세한 값 생성 (플레이스홀더 금지)
    4. **사용자 정보 보존**: user_info 값은 정확히 그대로 사용
    5. **컨텍스트 활용**: 리포트 내용 또는 이전 컨텍스트를 바탕으로 일관성 있는 값 생성
    
    **값 생성 가이드**:
    - **사용자 관련** (이름, 부서, 직급, 이메일): user_info에서 정확히 가져오기
    - **날짜/시간**: 한국어 형식으로 구체적인 날짜 (예: "2024년 12월 23일부터 27일까지")
    - **분류/유형**: 맥락에 맞는 구체적 카테고리
    - **설명/이유**: 상세하고 전문적인 업무 관련 설명
    - **기타**: 필드명의 의미를 분석하여 적절한 값 생성
    
    **중요**: 리포트 내용이 비어있으면 이전 컨텍스트와 워크플로우 단계를 활용하여 적절한 값을 생성하세요.
    
  expected_output: >
    text_form_keys의 각 키를 JSON 키로 사용하는 평면 JSON 객체.
    
    **출력 형식**:
    {
      "form_key_1": "구체적이고_상세한_값",
      "form_key_2": "전문적이고_현실적인_값"
    }
    
    **필수 준수사항**:
    - text_form_keys에 있는 모든 키 포함
    - text_form_keys에 없는 키는 절대 추가 금지
    - 중첩 구조나 그룹화 절대 금지
    - 유효한 JSON 형식 출력 